// Top 12 Functional Limitations per Anatomical Region
export const REGION_LIMITATIONS: Record<string, string[]> = {
  "Cervical": [
    "Difficulty turning head while driving",
    "Neck pain with computer or phone use",
    "Headache with sustained posture",
    "Pain when checking blind spot",
    "Limited rotation with daily activities",
    "Neck stiffness upon waking",
    "Pain lifting or carrying objects",
    "Neck fatigue at end of day",
    "Pain during reading or screen time",
    "Difficulty maintaining posture at desk",
    "Pain looking up or overhead",
    "Discomfort when lying on pillow"
  ],
  "Thoracic": [
    "Pain with prolonged sitting or standing",
    "Discomfort with deep breathing",
    "Mid-back fatigue during desk work",
    "Pain carrying objects in front",
    "Restricted rotation reaching behind",
    "Difficulty maintaining upright posture",
    "Pain during lifting or twisting",
    "Discomfort when reaching overhead",
    "Pain while sleeping or lying flat",
    "Stiffness during exercise or stretching",
    "Pain when coughing or sneezing",
    "Fatigue between shoulder blades"
  ],
  "Lumbar": [
    "Low back pain with bending or lifting",
    "Pain with prolonged sitting",
    "Pain when rising from a chair",
    "Difficulty tying shoes or dressing",
    "Morning stiffness in lower back",
    "Pain after standing or walking",
    "Discomfort carrying groceries",
    "Pain during exercise or running",
    "Difficulty bending to pick up items",
    "Pain while getting in/out of car",
    "Low back fatigue during work day",
    "Sleep disturbed by back pain"
  ],
  "Shoulder": [
    "Pain reaching overhead",
    "Difficulty dressing or fastening seatbelt",
    "Pain lifting objects to shelf height",
    "Night pain while sleeping on side",
    "Limited motion with grooming tasks",
    "Difficulty throwing or sports activities",
    "Pain carrying objects at side",
    "Weakness with overhead tasks",
    "Pain with reaching behind back",
    "Discomfort using phone or typing",
    "Pain lowering arm from overhead",
    "Limited endurance with repetitive reaching"
  ],
  "Elbow": [
    "Pain gripping or lifting objects",
    "Pain with typing or mouse use",
    "Discomfort with handshakes or twisting lids",
    "Pain carrying groceries or briefcase",
    "Difficulty lifting weights or pushups",
    "Pain holding phone or tools",
    "Elbow stiffness after rest",
    "Pain reaching or pulling",
    "Weak grip with daily tasks",
    "Pain throwing or sports activity",
    "Fatigue during repetitive arm use",
    "Pain during work tasks or crafts"
  ],
  "Wrist/Hand": [
    "Pain gripping or squeezing",
    "Difficulty opening jars or bottles",
    "Pain typing or texting",
    "Weakness lifting small objects",
    "Pain with pushing up from chair",
    "Discomfort writing or drawing",
    "Numbness or tingling with activity",
    "Pain twisting or turning handles",
    "Difficulty weight bearing on hand",
    "Fatigue with repetitive hand tasks",
    "Pain carrying small loads",
    "Loss of dexterity or coordination"
  ],
  "Hip": [
    "Pain standing from seated position",
    "Pain walking or climbing stairs",
    "Difficulty bending to put on shoes",
    "Pain with squatting or lunging",
    "Pain sleeping on side",
    "Stiffness after sitting",
    "Pain during exercise or sports",
    "Discomfort with prolonged standing",
    "Pain crossing legs",
    "Limited walking tolerance",
    "Pain when rolling in bed",
    "Pain entering or exiting car"
  ],
  "Knee": [
    "Pain climbing stairs or hills",
    "Pain squatting or kneeling",
    "Difficulty standing from seated position",
    "Pain walking or running",
    "Swelling after activity",
    "Pain during exercise",
    "Stiffness after sitting",
    "Pain carrying loads",
    "Instability or buckling",
    "Pain descending stairs",
    "Limited walking tolerance",
    "Discomfort sleeping with knee bent"
  ],
  "Ankle/Foot": [
    "Pain walking or standing",
    "Pain running or jumping",
    "Pain with stairs or inclines",
    "Discomfort on uneven ground",
    "Pain after long day on feet",
    "Pain wearing certain shoes",
    "Stiffness upon waking",
    "Pain during exercise",
    "Difficulty balancing on one leg",
    "Pain pushing off while walking",
    "Pain driving or braking",
    "Swelling after activity"
  ],
  "Brain/Head": [
    "Difficulty tolerating visual environments",
    "Headache that increases with cognitive or visual demand",
    "Difficulty with balance or spatial orientation",
    "Light or noise sensitivity",
    "Slowed processing speed",
    "Difficulty with reading endurance or comprehension",
    "Dizziness with head movements",
    "Fatigue that limits daily activities",
    "Difficulty with multitasking or divided attention",
    "Increased emotional reactivity or irritability",
    "Sleep disruption affecting daytime function",
    "Reduced exercise or activity tolerance"
  ]
};

export type LimitationRegionKey = keyof typeof REGION_LIMITATIONS;
