import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { FileText, Download, Eye } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Skeleton } from "@/components/ui/skeleton";

interface PatientLetter {
  id: string;
  episode_id: string;
  letter_type: string;
  title: string;
  content: string;
  generated_at: string;
}

export function PatientLetters() {
  const [letters, setLetters] = useState<PatientLetter[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedLetter, setSelectedLetter] = useState<PatientLetter | null>(null);
  const [viewDialogOpen, setViewDialogOpen] = useState(false);
  const { toast } = useToast();

  useEffect(() => {
    loadLetters();
  }, []);

  const loadLetters = async () => {
    try {
      setLoading(true);
      const { data: { user } } = await supabase.auth.getUser();
      
      if (!user) return;

      // Get all episode IDs the patient has access to
      const { data: accessData } = await supabase
        .from("patient_episode_access")
        .select("episode_id")
        .eq("patient_id", user.id)
        .eq("is_active", true);

      if (!accessData || accessData.length === 0) {
        setLetters([]);
        return;
      }

      const episodeIds = accessData.map(a => a.episode_id);

      // Get all letters for these episodes
      const { data: lettersData, error } = await supabase
        .from("patient_letters")
        .select("*")
        .in("episode_id", episodeIds)
        .order("generated_at", { ascending: false });

      if (error) throw error;

      setLetters(lettersData || []);
    } catch (error) {
      console.error("Error loading letters:", error);
      toast({
        title: "Error",
        description: "Failed to load letters",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const downloadLetter = (letter: PatientLetter) => {
    const blob = new Blob([letter.content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${letter.title.replace(/[^a-z0-9]/gi, '_')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Downloaded",
      description: "Letter downloaded successfully",
    });
  };

  const viewLetter = (letter: PatientLetter) => {
    setSelectedLetter(letter);
    setViewDialogOpen(true);
  };

  const getLetterTypeLabel = (type: string) => {
    switch (type) {
      case "employee":
        return "Employer Letter";
      case "school":
        return "School Letter";
      case "neuro_summary":
        return "Neurological Exam Summary";
      default:
        return "Letter";
    }
  };

  if (loading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Letters & Summaries
          </CardTitle>
          <CardDescription>
            Documents generated by your provider
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          {[1, 2].map((i) => (
            <div key={i} className="flex items-center justify-between p-4 border rounded-lg">
              <div className="space-y-2 flex-1">
                <Skeleton className="h-4 w-[200px]" />
                <Skeleton className="h-3 w-[150px]" />
              </div>
              <div className="flex gap-2">
                <Skeleton className="h-9 w-20" />
                <Skeleton className="h-9 w-24" />
              </div>
            </div>
          ))}
        </CardContent>
      </Card>
    );
  }

  if (letters.length === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Letters & Summaries
          </CardTitle>
          <CardDescription>
            Documents generated by your provider
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="text-center py-8 text-muted-foreground">
            <FileText className="h-12 w-12 mx-auto mb-3 opacity-50" />
            <p>No letters or summaries available yet</p>
            <p className="text-sm mt-1">
              Your provider can generate letters for you during your care
            </p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <>
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Letters & Summaries
          </CardTitle>
          <CardDescription>
            Documents generated by your provider
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          {letters.map((letter) => (
            <div
              key={letter.id}
              className="flex items-center justify-between p-4 border rounded-lg hover:bg-accent/50 transition-colors"
            >
              <div className="flex-1">
                <h4 className="font-medium">{letter.title}</h4>
                <p className="text-sm text-muted-foreground">
                  {getLetterTypeLabel(letter.letter_type)} • {new Date(letter.generated_at).toLocaleDateString()}
                </p>
              </div>
              <div className="flex gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => viewLetter(letter)}
                >
                  <Eye className="h-4 w-4 mr-1" />
                  View
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => downloadLetter(letter)}
                >
                  <Download className="h-4 w-4 mr-1" />
                  Download
                </Button>
              </div>
            </div>
          ))}
        </CardContent>
      </Card>

      <Dialog open={viewDialogOpen} onOpenChange={setViewDialogOpen}>
        <DialogContent className="max-w-3xl max-h-[80vh]">
          <DialogHeader>
            <DialogTitle>{selectedLetter?.title}</DialogTitle>
          </DialogHeader>
          <ScrollArea className="h-[60vh] w-full rounded-md border p-4">
            <div className="whitespace-pre-wrap text-sm">
              {selectedLetter?.content}
            </div>
          </ScrollArea>
          <div className="flex justify-end gap-2">
            <Button
              variant="outline"
              onClick={() => selectedLetter && downloadLetter(selectedLetter)}
            >
              <Download className="h-4 w-4 mr-2" />
              Download
            </Button>
            <Button onClick={() => setViewDialogOpen(false)}>Close</Button>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
