import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";
import { Share2, Download, Mail, Loader2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

interface ShareProgressProps {
  episodeId: string;
  patientName: string;
}

export default function ShareProgress({ episodeId, patientName }: ShareProgressProps) {
  const { toast } = useToast();
  const [generating, setGenerating] = useState(false);

  const generateProgressSummary = async () => {
    setGenerating(true);
    try {
      // Fetch episode and scores
      const { data: episode, error: episodeError } = await supabase
        .from("episodes")
        .select("*")
        .eq("id", episodeId)
        .single();

      if (episodeError) throw episodeError;

      const { data: scores, error: scoresError } = await supabase
        .from("outcome_scores")
        .select("*")
        .eq("episode_id", episodeId)
        .order("recorded_at", { ascending: true });

      if (scoresError) throw scoresError;

      // Calculate improvements
      const improvements: Record<string, { baseline: number; latest: number; change: number }> = {};
      scores?.forEach(score => {
        if (!improvements[score.index_type]) {
          improvements[score.index_type] = { baseline: 0, latest: 0, change: 0 };
        }
        if (score.score_type === "baseline") {
          improvements[score.index_type].baseline = score.score;
        }
        if (score.score_type === "discharge" || score.score_type === "followup") {
          improvements[score.index_type].latest = score.score;
        }
      });

      Object.keys(improvements).forEach(key => {
        const imp = improvements[key];
        if (imp.baseline && imp.latest) {
          imp.change = Math.round(((imp.baseline - imp.latest) / imp.baseline) * 100);
        }
      });

      // Generate summary text
      let summary = `🎯 Rehabilitative Care Progress Summary\n\n`;
      summary += `Patient: ${patientName}\n`;
      summary += `Treatment Area: ${episode.region}\n`;
      if (episode.diagnosis) summary += `Diagnosis: ${episode.diagnosis}\n`;
      summary += `\n📊 Progress:\n`;
      
      Object.entries(improvements).forEach(([index, imp]) => {
        if (imp.change > 0) {
          summary += `• ${index}: ${imp.change}% improvement (${imp.baseline} → ${imp.latest})\n`;
        }
      });

      summary += `\n✨ Generated by PPC Outcome Registry`;

      // Copy to clipboard
      await navigator.clipboard.writeText(summary);

      toast({
        title: "Progress Summary Copied!",
        description: "You can now paste and share your progress",
      });

      return summary;
    } catch (error: any) {
      toast({
        title: "Failed to Generate Summary",
        description: error.message,
        variant: "destructive",
      });
    } finally {
      setGenerating(false);
    }
  };

  const handleShare = async () => {
    const summary = await generateProgressSummary();
    if (summary && navigator.share) {
      try {
        await navigator.share({
          title: "My Rehabilitative Care Progress",
          text: summary,
        });
      } catch (error) {
        // User cancelled or share not supported
        console.log("Share cancelled or not supported");
      }
    }
  };

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline" className="gap-2">
          <Share2 className="h-4 w-4" />
          Share My Progress
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Share Your Progress</DialogTitle>
          <DialogDescription>
            Generate a summary of your recovery journey to share with family or your primary care physician
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-3 pt-4">
          <Button
            onClick={generateProgressSummary}
            disabled={generating}
            className="w-full gap-2"
          >
            {generating ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <Download className="h-4 w-4" />
            )}
            Copy to Clipboard
          </Button>
          {navigator.share && (
            <Button
              onClick={handleShare}
              disabled={generating}
              variant="outline"
              className="w-full gap-2"
            >
              <Share2 className="h-4 w-4" />
              Share Via...
            </Button>
          )}
          <p className="text-xs text-muted-foreground text-center">
            Your progress summary includes outcome scores and improvements
          </p>
        </div>
      </DialogContent>
    </Dialog>
  );
}